version: "3.8"
services: 
  mosquitto:
    image: eclipse-mosquitto:1.6.10
    container_name: mosquitto_iot
    restart: always
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - $HOME/docker/volumes/mosquitto/data:/mosquitto/data
      - $HOME/docker/volumes/mosquitto/log:/mosquitto/log
    ports: 
      - 1883:1883
      - 9003:9003
